special_bonus_morphling_attribute_shift_15_attributes = class({})

LinkLuaModifier( "modifier_special_bonus_morphling_attribute_shift_15_attributes", "heroes/hero_morphling/talents/special_bonus_morphling_attribute_shift_15_attributes/modifier_special_bonus_morphling_attribute_shift_15_attributes", LUA_MODIFIER_MOTION_NONE )

function special_bonus_morphling_attribute_shift_15_attributes:GetIntrinsicModifierName()
	return "modifier_special_bonus_morphling_attribute_shift_15_attributes" 
end

