special_bonus_morphling_magic_resistance15pct = class({})

LinkLuaModifier( "modifier_special_bonus_morphling_magic_resistance15pct", "heroes/hero_morphling/talents/special_bonus_morphling_magic_resistance15pct/modifier_special_bonus_morphling_magic_resistance15pct", LUA_MODIFIER_MOTION_NONE )

function special_bonus_morphling_magic_resistance15pct:GetIntrinsicModifierName()
	return "modifier_special_bonus_morphling_magic_resistance15pct"
end
