special_bonus_morphling_wave_use_modifier_attack = class({})

LinkLuaModifier( "modifier_special_bonus_morphling_wave_use_modifier_attack", "heroes/hero_morphling/talents/special_bonus_morphling_wave_twice_attack/modifier_special_bonus_morphling_wave_use_modifier_attack", LUA_MODIFIER_MOTION_NONE )

function special_bonus_morphling_wave_use_modifier_attack:GetIntrinsicModifierName()
	return "modifier_special_bonus_morphling_wave_use_modifier_attack" 
end
